apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane-idp
  namespace: dev
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crossplane-idp-role
rules:
- apiGroups: ["apiextensions.crossplane.io"]
  resources: ["compositeresourcedefinitions"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apiextensions.crossplane.io"]
  resources: ["compositions"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["crd"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crossplane-idp-rolebinding
subjects:
- kind: ServiceAccount
  name: crossplane-idp
  namespace: dev
roleRef:
  kind: ClusterRole
  name: crossplane-idp-role
